[tox]
isolated_build = True
envlist =
    lint
    py312

[testenv:lint]
deps =
    ruff
    mypy
commands =
    ruff format
;    ruff check
;    mypy .

[testenv]
deps =
    coverage
    pytest
commands =
    coverage run --source=python_polarion_utils --branch -m pytest . --junitxml="junittest.xml"
    coverage report -m --fail-under 2
    coverage xml

[pytest]
addopts =
    --ignore=python_polarion_utils/api/test_data.py
